### ISSUE TITLE
3D pose 似乎没有方向感

### ISSUE THREAD

**Issue by simple123456T** [Liangdacai/Human3d-keypoints#1]
跪求大佬的 “基于单目相机，输入RGB，实时估计人体3d姿态算法，可以在Unity下驱动虚拟人模型哦......” 源码，

ps: 在B站似乎评论下方的GitHub链接被和谐了

**Comment by Liangdacai** [comment]
demo for camera的第二个链接，方向还好，最近放出来的这个有点粗糙，这个对2d检测的要求挺高的，我就直接用的别人的，以前做的对2d点的检测做了处理，加了跟踪，所以很稳定。
