### ISSUE TITLE
rot设置

### ISSUE THREAD

**Issue by simple123456T** [Liangdacai/Human3d-keypoints#12]
老师，如何才能获取自己相机的rot

**Comment by Liangdacai** [comment]
相机标定，可以计算出相机的参数

**Comment by simple123456T** [comment]
我跑了新的main文件之后感觉效果没有你视频里的好，是不是需要替换我自己相机的rot

**Comment by Liangdacai** [comment]
最新的视频吗？还是以前那个视频？最新视频用的普通相机，以前那个视频用的是广角工业相机，会有一定的影响

**Comment by simple123456T** [comment]
最新的视频，https://www.bilibili.com/video/BV18Y4y147ST?spm_id_from=333.999.0.0 
您的rot是怎么计算出来的

**Comment by Liangdacai** [comment]
这个不是计算的，这个是直接用的h36m的生成数据的相机参数

**Comment by simple123456T** [comment]
这个和自己的相机有关吗

**Comment by Liangdacai** [comment]
你不做2d投影，就和相机参数没有关系，相机获取pose，会归一化到h36m的相机分辨率下，网络也仅仅只学习了h36m相机空间下估计的能力，获取结果只需用它的参数转换到世界坐标中，和我们的输入相机没有关系

**Comment by simple123456T** [comment]
哦哦，明白了，谢谢老师
