### ISSUE TITLE
后续是否还会更新

### ISSUE THREAD

**Issue by simple123456T** [Liangdacai/Human3d-keypoints#13]
后续还会更新到视频里流畅的效果吗

**Comment by Liangdacai** [comment]
这就是更新后的了啊，视频里面的就是我用这份代码直接跑的摄像头录的，至于以前那个，用的是广角摄像头，活动空间广，效果看起来不错，这份代码，用广角摄像头跑，就能跑出以前那种效果，但需要对人跟踪，避免出现丢帧现象，不然效果会不理想

**Comment by simple123456T** [comment]
能用paddle 的2D关键点检测模型（coco数据集基于hrnet）替换你的2d部分吗

**Comment by Liangdacai** [comment]
可以的，这些是工程上的东西

**Comment by simple123456T** [comment]
那使用openpose去替代你的2d部分可以吗

**Comment by Liangdacai** [comment]
任何2d kps检测部分都可以替代，只需要转换成h36m数据的kps顺序即可

**Comment by simple123456T** [comment]
哦哦， “对人跟踪”该如何实现呢

**Comment by Liangdacai** [comment]
人物跟踪，开源的算法很多，如果简单的跟踪，可用简单欧氏距离做判断，如果跟丢，当前帧用过去帧替代，方式很多

**Comment by simple123456T** [comment]
哦哦，谢谢
