### ISSUE TITLE
相机坐标转换成空间坐标，代码是加在这里吗

### ISSUE THREAD

**Issue by simple123456T** [Liangdacai/Human3d-keypoints#9]
![image](https://user-images.githubusercontent.com/104408880/167232632-2fb47305-62f2-4601-88cf-8091a01d6df2.png)

**Comment by Liangdacai** [comment]
main.py已更新，问题都解决了，代码有点乱，自行补脑

**Comment by simple123456T** [comment]
XD， 谢谢大佬
